### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by ream88** [bmoren/p5.collide2D#18]
Please publish this package on npmjs.com 😊

**Comment by MrKhoaBean** [comment]
Here: https://www.npmjs.com/package/p5collide

**Comment by bmoren** [comment]
I still want to publish this on npmjs as a non-moduleized, un-modified version at some point in the near future. I appreciate the approach that was taken in that version, but it adds an additional hurdle for beginners in needing to learn and utilize class instantiation and modules which is potentially prohibitive to them using the library..

**Comment by bmoren** [comment]
done!
https://www.npmjs.com/package/p5.collide2d
