### ISSUE TITLE
Support for instantiated sketches?

### ISSUE THREAD

**Issue by mexitalian** [bmoren/p5.collide2D#2]
Is there a way to use this library from [an instantiated sketch](http://p5js.org/examples/examples/Instance_Mode_Instantiation.php), currently I can call the the collide2d methods using the namespace created, i.e. **p**.collideCirclePoly() but when subsequent methods are called an error is thrown as these are not found in the global scope.

Chrome: _index.js:258 Uncaught ReferenceError: collideLineCircle is not defined_

Could be I'm missing something simple.
Many thanks.

**Comment by chiunhau** [comment]
I got `p5.collide2d.js:149 Uncaught ReferenceError: _collideDebug is not defined` in instance mode 😞

**Comment by EseOkonofua** [comment]
I have the same issue anyway to fix this?

**Comment by conradoqg** [comment]
I've created a PR for that.
#4 - makes collide2d work with instantiated sketches.

**Comment by bmoren** [comment]
@conradoqg 's changes have been merged into the master branch, thank you!
