### ISSUE TITLE
statically hosted file

### ISSUE THREAD

**Issue by SaltyBuckets** [bmoren/p5.collide2D#21]
need to add a statically hosted file that can be used to embed script in sketches without actually downloading it

**Comment by bmoren** [comment]
Are you requesting CDN support? 

If so, most CDN's require a minimum threshold of stars or some other metric to be included, and this library does not meet them unfortunately.

you can get to the static file using the raw github usercontent files or useing JSDelivr

eg:

`https://cdn.jsdelivr.net/gh/bmoren/p5.collide2D@0.6/p5.collide2d.min.js`

or adding the following to your index.js file

   ` <script src="https://cdn.jsdelivr.net/gh/bmoren/p5.collide2D@0.6/p5.collide2d.min.js"></script>`

just above the following line:

    `<script src="sketch.js"></script>`

This isn't really a feature of the library, but more of a github thing, so hopefully this helps!

**Comment by bmoren** [comment]
This might be even better, since it'll use the most recent version automatically:

`https://cdn.jsdelivr.net/gh/bmoren/p5.collide2D/p5.collide2d.min.js`

**Comment by GoToLoop** [comment]
Here's an "index.html" template w/ p5js + p5.collide2D libs:
```html
<script defer src=https://cdn.JsDelivr.net/npm/p5></script>
<script defer src=https://cdn.JsDelivr.net/gh/bmoren/p5.collide2D/p5.collide2d.min.js></script>
<script defer src=sketch.js></script>
```

**Comment by SaltyBuckets** [comment]
thanks!
