### ISSUE TITLE
Rotating rectangle

### ISSUE THREAD

**Issue by Hamme05** [bmoren/p5.collide2D#22]
How do I detect collision on a rotated rectangle?

**Comment by bmoren** [comment]
Hi Herman, Thanks for using the library!
This isn't really the best place for asking troubleshooting questions, best to keep those on the official p5.js forum and to keep the discussion here to development issues and bugs. 

looks like someone has taken a look at this question over on the forum, you can join in on that conversation here: https://discourse.processing.org/t/rotated-polygons-with-collision-detection/10755

good luck!
