### ISSUE TITLE
CDN support?

### ISSUE THREAD

**Issue by deiangi** [bmoren/p5.collide2D#3]
Hey great work on the collision detection routines.

How can we add that to CDN?

**Comment by conradoqg** [comment]
The latest version has the minified version and can be accessed by https://cdn.rawgit.com/bmoren/p5.collide2D/cfb05302/p5.collide2d.min.js

**Comment by bmoren** [comment]
Thanks!

**Comment by GoToLoop** [comment]
Another CDN: http://CDN.JSDelivr.net/gh/bmoren/p5.collide2D@0.5/p5.collide2d.min.js  
But it'd be better if this repo followed https://SemVer.org/ versioning convention for its releases though.
