### ISSUE TITLE
move live examples to the p5.js editor within a collection

### ISSUE THREAD

**Issue by bmoren** [bmoren/p5.collide2D#30]

**Comment by wisehackermonkey** [comment]
could be implemented as iframs for each example
for example

```html
  <iframe src="https://editor.p5js.org/wisemonkey/embed/RqgNakFCQ"></iframe>
```

**Comment by dipamsen** [comment]
Wouldn't this make sense to have all the examples on the account of creator?

**Comment by bmoren** [comment]
yes, we will make a new account just for this purpose. 

I think what @wisehackermonkey is suggesting is that we replace the code examples in the readme with live runnable versions using an embeded version of the p5 web editor

**Comment by bmoren** [comment]
this really combines 2 ideas, getting the live examples moved over to the web editor, and getting the documentation examples there as well. it'd be great to have a base set of examples like that to work on! 

*if anyone is interested in working on this*: please feel free to get them all migrated onto a fresh p5 web editor account 
& please set it up using a fresh email account/password and share with me! otherwise I'll get to it when I have time!

**Comment by rikdewit** [comment]
I think this idea is great to visualize the examples. As you can't embed javascript in the readme, would you place all the examples in a p5 web-editor project and link to it?

**Comment by wisehackermonkey** [comment]
@rikdewit would you be willing to create setup examples on p5?

**Comment by rikdewit** [comment]
Yes I'm on it.

**Comment by bmoren** [comment]
awesome, can you please set these up on a new account so they are independent of anyone's personal projects

**Comment by rikdewit** [comment]
This is the collection of examples. https://editor.p5js.org/p52dcollide/collections/taUUdSGhj
@bmoren I will send you the account login and password.

**Comment by bmoren** [comment]
incredible!

Any chance you'd be up for converting the in context examples  as well?

  + [Basic Usage](https://bmoren.github.io/p5.collide2D/examples/basic/index.html)
  + [Button with a callback](https://bmoren.github.io/p5.collide2D/examples/basicButton/index.html)
  + [Object oriented collision](https://bmoren.github.io/p5.collide2D/examples/objectCollision/index.html)
  + [Randomly placing objects without touching](https://bmoren.github.io/p5.collide2D/examples/randomPlacement/index.html)
  + [Swords Game](https://bmoren.github.io/p5.collide2D/examples/swords/index.html)

**Comment by rikdewit** [comment]
@bmoren Do you have an email I can send it to?

**Comment by bmoren** [comment]
ben@benmoren.com

**Comment by wisehackermonkey** [comment]
@rikdewit awesome work!  Thanks!
