### ISSUE TITLE
CDN links for NPM still point to v.0.6

### ISSUE THREAD

**Issue by GoToLoop** [bmoren/p5.collide2D#34]
These 2 CDN links below:
1. https://cdn.JsDelivr.net/npm/p5.collide2d
2. https://Unpkg.com/p5.collide2d

are grabbing the previous p5.collide2d version 0.6 instead of the newly released 0.7!

We can also navigate all files via these links:
1. https://cdn.JsDelivr.net/npm/p5.collide2d/
2. https://Unpkg.com/p5.collide2d/

**Comment by bmoren** [comment]
noted, will need to bump the version number to achieve this, I'll have a look later this afternoon or evening.

thanks for the catch!

**Comment by bmoren** [comment]
I've bumped the number, have a look after things propagate and let me know if there is an issue. I've also added the CDN links to the readme

**Comment by wisehackermonkey** [comment]
awesome!
`I've also added the CDN links to the readme` you read my mind!
