### ISSUE TITLE
Interior option for collidePolyPoly()

### ISSUE THREAD

**Issue by tektsu** [bmoren/p5.collide2D#37]
I was having issues with collidePolyPoly() not detecting collisions when one polygon is inside another. Looking at the source I see that collidePolyPoly() detects when p2 is inside p1, but not when p1 is inside p2. It seems like that is an equally valid collision, unless I am misunderstanding something.

**Comment by bmoren** [comment]
You're right! It should absolutely work the other way around as well. Thanks for the report.

**Comment by tektsu** [comment]
I have submitted a pull request for a fix for this. While looking into it, I found that there was also a problem with collidePointPoly() when the y coordinate of the point is the same of y of two or more vertices, but is not otherwise found on any sides of the polygon. My pull request also contains a fix for this.

My test program to ensure this works (based on your collidePolyPoly() example):


```
 //example adapted from Jeffrey Thompson
 var hit = false;
 var poly = new Array(8);
 var randomPoly = new Array(8);
 function setup() {
    createCanvas(windowWidth,windowHeight);
    //collideDebug(true) //enable debug mode

    //generate a uniform sided polygon
    var angle = TWO_PI / poly.length;
    for (var i=0; i<poly.length; i++) {
        var a = angle * i;
        var x = 300 + cos(a) * 100;
        var y = 200 + sin(a) * 100;
        poly[i] = createVector(x,y);
    }

    // create a 2nd larger polygon
    for (var i=0; i<randomPoly.length; i++) {
        var a = angle * i;
        var x = 300 + cos(a) * 150;
        var y = 200 + sin(a) * 150;
        randomPoly[i] = createVector(x,y);
    }
 }
 function draw() {
    background(255);
    fill(128, 0, 0, 128);
    // update random polygon to mouse position
    var mouse = createVector(mouseX, mouseY);
    var diff = mouse.sub(randomPoly[0]);

    for (i=0; i < randomPoly.length; i++) {
        randomPoly[i].add(diff);
    }

    beginShape();
    for(i=0; i < randomPoly.length; i++){
        vertex(randomPoly[i].x,randomPoly[i].y);
    }
    endShape(CLOSE);
    beginShape();
    //draw the polygon from the created Vectors above.
    for(i=0; i < poly.length; i++){
        vertex(poly[i].x,poly[i].y);
    }
    endShape(CLOSE);

    hit = collidePolyPoly(poly,randomPoly,true);

    stroke( (hit) ? color("red") : 0);
    print("colliding? " + hit);

 }

```

**Comment by bmoren** [comment]
The PR has been merged, thank you for your work on this! glad to have this support and the bugs worked out!
